server:
    logLevel: RTCSTATS_LOG_LEVEL
    appEnvironment: RTCSTATS_ENVIRONMENT

amplitude:
    key: RTCSTATS_AMPLITUDE_KEY

firehose:
    region: RTCSTATS_FIREHOSE_AWS_REGION
    meetingStatsStream: RTCSTATS_FIREHOSE_MEETING_STREAM
    pcStatsStream: RTCSTATS_FIREHOSE_PC_STREAM

s3:
    region: RTCSTATS_S3_AWS_REGION
    bucket: RTCSTATS_S3_BUCKET

dynamo:
    tableName: RTCSTATS_METADATA_TABLE
