server:
    port: 3000

s3:
    accessKeyId:
    secretAccessKey:
    region:
    bucket:

firehose:
    accessKeyId:
    secretAccessKey:
    region:
    stream:

postgres:
    user:
    host:
    password:
    database:

appenders:
    - type: file
      layout:
          type: pattern
          pattern: "%d{ISO8601}   %5p [%t]    %m"
      filename: rtcstats-server_access
    - type: logLevelFilter
      level: ERROR
      appender:
          type: file
          layout:
              type: pattern
              pattern: "%d{ISO8601}   %5p [%t]    %m"
          filename: rtcstats-server_error

github:
    client_id: GITHUB_CLIENT_ID
    client_secret: GITHUB_SECRET
    callback_url: GITHUB_CALLBACK_URL
