server:
    port: 3000
    metrics: 8095
    # Set to true if you've a LB in front of RTCStats and you are obtaining
    # its IP address as part of the X-Forwarded-For header
    skipLoadBalancerIp: false
    logLevel: info
    jsonConsoleLog: true
    # The provided certificates are intended for local testing usign a HTTPS server
    useHTTPS: false
    tempPath : 'temp'

features:
    disableFeatExtraction: false
    # White list of client related features to be extracted possible values can be found in featured-client.js
    # inside the module.exports object e.g. ['origin', 'getUserMediaSuccess', 'calledMediadevicesGetUserMedia']
    clientFeat: ['calledGetUserMediaRequestingScreen',
                 'calledGetUserMediaRequestingAudio',
                 'calledGetUserMediaRequestingVideo',
                 'firstAudioTrackLabel',
                 'firstVideoTrackLabel']
    connectionFeat: [
                     'ICEFailure',
                     'connectionTime',
                     'numberOfRemoteStreams',
                     'sessionDuration',
                     'bytesTotal',
                     'stats',
                     'firstCandidatePair',
                     'sfuP2P']

amplitude:
    key:

s3:
    accessKeyId:
    secretAccessKey:
    region:
    bucket:
    useIAMAuth: true

firehose:
    accessKeyId:
    secretAccessKey:
    region:
    stream:

gcp:
    bucket:
    dataset:
    table:
    maxFlushTime:
    bufferSize:

github:
    client_id: GITHUB_CLIENT_ID
    client_secret: GITHUB_SECRET
    callback_url: GITHUB_CALLBACK_URL

dynamo:
  tableName:

