name: RTCStats-docker-latest-image

on:
  pull_request:
    types: [closed]
  push:
    branches:
      - github-action

jobs:
  generate-image:
    name: Build docker image
    runs-on: ubuntu-latest
    env:
      DOCKER_HUB_USERNAME: juandebravo
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Generate Docker image and push to Docker hub
        run: |
          docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_ACCESS_TOKEN
          make push